package eg.com.ef.tsa.lookupapi.domain;

/**
 * Write side of {@link Lookup}. Kept separate from the read side because two entities
 * can't satisfy it with their real fields: Bank has no CODE column, so setCode() is a
 * no-op there; ErrorCode has no separate business code distinct from its own primary
 * key, so setCode() is a no-op there too - see {@link Bank} and {@link ErrorCode}.
 */
public interface MutableLookup extends Lookup {
    void setCode(String code);

    void setArName(String arName);

    void setEnName(String enName);

    default void setArDescription(String value) {
        // no-op for the 18 entities without a description pair
    }

    default void setEnDescription(String value) {
        // no-op for the 18 entities without a description pair
    }

    /**
     * Assigns the entity's own primary key, for the one case where it's supplied by the
     * caller rather than generated by a DB sequence: {@link ErrorCode}, whose id IS its
     * CODE column. A no-op for every other (Long-surrogate-id) entity - those get their
     * id from the DB on save, never from here. {@link eg.com.ef.tsa.lookupapi.service.LookupService#create}
     * calls this before {@code save()} only when the type's idType is STRING.
     */
    default void assignClientSuppliedId(String id) {
        // no-op for every Long-id entity
    }
}
