-- Intentionally a no-op.
--
-- All 20 lookup tables (BANK, CURRENCY, STATUS, ...) already exist and are owned by
-- the legacy WebLogic application's schema. This service is baselined against that
-- existing state (see application.yml: flyway.baseline-on-migrate=true) rather than
-- creating them - Flyway's job here is versioning FUTURE schema changes to this
-- bounded context (e.g. adding a CODE column to BANK for consistency, or an ACTIVE
-- flag for soft-delete), not the initial creation.
--
-- The next real migration goes in V2__<description>.sql.
